name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main


jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      FLUTTER_VERSION: "3.22.2"

      runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - run: flutter --version
    - name: Install dependencies
      run: cd mobile_app && flutter pub get

    - name: create environment
      run: cd mobile_app && echo "HOST_URL:clement.lagier:3000\nCACHING_KEY=test_key" > .env

    - name: Build Web
      run: cd mobile_app && flutter build web --release

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
